import './globals.css';
import { Quicksand } from 'next/font/google';
import Header from './components/Header';
import '@fortawesome/fontawesome-svg-core/styles.css';
import {NextAuthProvider} from '@/providers/auth-provider';

const workSans = Quicksand({ variable: '--font-quicksand', subsets: ['latin'] });
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <title>QualiUN</title>
      </head>

        <body
            className={`${workSans.variable} font-sans tracking-tighter w-full flex flex-col justify-center items-center`}
        >
        <NextAuthProvider>
            <Header/>
            {children}
        </NextAuthProvider>
        </body>
        </html>
    );
}
